name: publish
on: [push]
jobs:
publish-hello-docker-image:
runs-on: nginx:1.10.1-alpine 
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the weather-app:latest image
run: |
       docker build . --tag ghcr.io/deselikem/weather-app:latest
       docker run ghcr.io/deselikem/weather-app:latest
       docker push ghcr.io/deselikem/weather-app:latest
